# External Secrets Development Environment Values
global:
  namespace: fx-orleans-dev
  environment: dev
  region: us-east-2

# AWS configuration for us-east-2
aws:
  region: us-east-2

# Service Account with correct IRSA role
serviceAccount:
  create: true
  name: external-secrets-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::754345703722:role/fx-orleans-dev-external-secrets"