# More info around this file at https://www.git-town.com/configuration-file

[branches]
main = "main"
perennials = []
perennial-regex = ""

[create]
new-branch-type = "feature"
share-new-branches = "push"

[hosting]
dev-remote = "origin"
# forge-type = ""
# origin-hostname = ""

[ship]
delete-tracking-branch = true
strategy = "squash-merge"

[sync]
feature-strategy = "compress"
perennial-strategy = "rebase"
prototype-strategy = "compress"
push-hook = true
tags = true
upstream = true
