apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventserver.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "eventserver.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "eventserver.selectorLabels" . | nindent 4 }}