{{- if .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.headlessServiceName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    {{- range .Values.headlessService.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .name }}
    {{- end }}
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
{{- end }}