using Keycloak.AuthServices.Authentication;
using FastEndpoints;

using FastEndpoints.Swagger;
using Users;


var builder = WebApplication.CreateBuilder(args);

// load Users assembly
//var userAssembly = Assembly.Load("Users");
//
// clear autogenerated logging providers
//builder.Logging.ClearProviders();

//
// Add open-telemetry common/ServiceCollectionExtensions.cs
//builder.Services.AddFx();

//
// configure opentelemetry logging common/ServiceCollectionExtensions.cs
//builder.Logging.AddOpenTelemetryLoggingFx();

//
// Add Orleans
//builder.Host.AddOrleans();

builder.Services.AddFastEndpoints(options => {
    options.Assemblies = [ UserAssembly.Get() ];
    })
.SwaggerDocument( o =>
    {
        o.AutoTagPathSegmentIndex = 2;
        o.TagCase = TagCase.TitleCase;
        o.TagStripSymbols = true; //this option is new
    });

// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddKeycloakWebAppAuthentication(builder.Configuration);
//builder.Services.AddKeycloakWebApiAuthentication(builder.Configuration);

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

//
// Add Swagger Support
app.UseFastEndpoints().UseSwaggerGen();

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.MapRazorPages().RequireAuthorization();
app.Logger.LogInformation("Starting FX Application");
app.Run();
