using Keycloak.AuthServices.Authentication;
using OpenTelemetry.Logs;
using OpenTelemetry.Metrics;
using OpenTelemetry.Trace;
using org.fortium.fx;


var builder = WebApplication.CreateBuilder(args);
//
// clear autogenerated logging providers
builder.Logging.ClearProviders();

//
// Add open-telemetry
builder.Services.AddOpenTelemetryFx();

builder.Logging.AddOpenTelemetryLoggingFx();

// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddKeycloakWebAppAuthentication(builder.Configuration);
//builder.Services.AddKeycloakWebApiAuthentication(builder.Configuration);

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.MapRazorPages().RequireAuthorization();

app.Run();
