apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blazor-frontend.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "blazor-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "blazor-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        prometheus.io/scrape: "{{ .Values.monitoring.enabled }}"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        {{- include "blazor-frontend.selectorLabels" . | nindent 8 }}
        version: {{ .Values.image.tag | quote }}
    spec:
      serviceAccountName: {{ include "blazor-frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            # Application environment
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
            - name: ASPNETCORE_URLS
              value: {{ .Values.env.ASPNETCORE_URLS | quote }}
            - name: TZ
              value: {{ .Values.env.TZ | quote }}
            - name: LOGGING_LEVEL
              value: {{ .Values.logging.level | quote }}
            
            # AWS configuration
            - name: AWS_REGION
              value: {{ .Values.aws.region | quote }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region | quote }}
            
            # EventServer configuration from External Secret
            - name: EVENTSERVER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalServices.eventserver.secretName }}
                  key: url
                  optional: true
            
            # Keycloak configuration from External Secret
            - name: KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalServices.keycloak.secretName }}
                  key: url
                  optional: true
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalServices.keycloak.secretName }}
                  key: client_secret
                  optional: true
          
          {{- if .Values.healthcheck.enabled }}
          livenessProbe:
            {{- toYaml .Values.healthcheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.healthcheck.readinessProbe | nindent 12 }}
          {{- end }}
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          volumeMounts:
            - name: config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
              readOnly: true
            {{- range .Values.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .readOnly }}
              readOnly: {{ .readOnly }}
              {{- end }}
            {{- end }}
      
      volumes:
        - name: config
          configMap:
            name: {{ include "blazor-frontend.fullname" . }}
        {{- range .Values.volumes }}
        - name: {{ .name }}
          {{- if .emptyDir }}
          emptyDir: {}
          {{- else if .configMap }}
          configMap:
            name: {{ .configMap.name }}
          {{- else if .secret }}
          secret:
            secretName: {{ .secret.secretName }}
          {{- end }}
        {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}