{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "blazor-frontend.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "blazor-frontend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "blazor-frontend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.serviceMonitor.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: 10s
      honorLabels: true
      {{- if .Values.monitoring.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.monitoring.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.monitoring.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
{{- end }}